image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375/

stages:
  - build

services:
  - name: docker:18-dind
    command: ["--max-concurrent-downloads", "10", "--max-concurrent-uploads", "10"]

before_script:
  - docker info

docker:
  stage: build
  tags:
    - k8s-medium
  script:
    - echo "${dockerhub_password}" | docker login --username=${dockerhub_username} --password-stdin
    - docker build --tag stackstate/atlantis-terragrunt:$CI_BUILD_REF_NAME --tag stackstate/atlantis-terragrunt:$CI_COMMIT_SHORT_SHA --tag stackstate/atlantis-terragrunt:latest .
    - for tag in latest $CI_BUILD_REF_NAME $CI_COMMIT_SHORT_SHA ; do docker push stackstate/atlantis-terragrunt:$tag ; done
