image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

default:
  services:
    - name: docker:dind
      command:
        - --experimental

stages:
  - build

before_script:
  - docker info

docker:
  stage: build
  script:
    - echo "${docker_password}" | docker login --username=${docker_user} --password-stdin docker.io
    - docker build --squash --compress --no-cache --tag stackstate/atlantis-terragrunt:${CI_BUILD_REF_NAME} --tag stackstate/atlantis-terragrunt:${CI_COMMIT_SHORT_SHA} --tag stackstate/atlantis-terragrunt:latest .
    - for tag in latest ${CI_BUILD_REF_NAME} ${CI_COMMIT_SHORT_SHA} ; do docker push stackstate/atlantis-terragrunt:$tag ; done
